name: ESLint (reviewdog)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  checks: write   # needed for github-pr-check reporter

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: Run ESLint via reviewdog (Checks)
        uses: reviewdog/action-eslint@2fee6dd72a5419ff4113f694e2068d2a03bb35dd # v1.33.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check   # inline annotations in Checks tab
          level: warning              # or 'error'
          eslint_flags: .
